#!/bin/bash

find_all_folders(){
    # Parameters
    SUCCESSOR_DIR=$1

    # Functions
    helpFunction(){
        echo ""
        echo "Usage: find_all_folders <path>"
        echo ""
        echo -e "  -h/--help  \tHelp"
        echo -e "  <path>     \tGive the path as base dir to start searching,"
        echo -e "             \tabsolute or relative paths are both ok."
        exit 1
    }

    findAllFolder(){
        local SEARCH_BASE=$1
        for sub in $(ls ${SEARCH_BASE}); do
            if (test -d ${SEARCH_BASE}/${sub}) ; then
                SUCCESSOR_DIR=$( cd ${SEARCH_BASE}/${sub} && pwd)
                echo "${SEARCH_BASE}/${sub} is a folder."
                findAllFolder ${SUCCESSOR_DIR}
            fi
        done
    }

    main(){
        if [ $# -eq 0 ] || [ $# -gt 1 ] || [ $1 = "-h" ] || [ $1 = "--help" ] ; then
            helpFunction
        else
            BASE_DIR=$(cd $1 && pwd)
            echo -e "\033[47;30m current dir is: $BASE_DIR \033[0m"
            findAllFolder ${BASE_DIR}
        fi
    }

    # Entry
    main $@
}

find_all_folders $@