#!/bin/bash
set -e  # exit on first error

ITER=0

helpFunction(){
    echo ""
    echo "Usage: find_git_repo <path>"
    echo ""
    echo -e "  -h/--help   \tHelp"
    echo -e "  <path>      \tGive the path as base dir to start searching,"
    echo -e "              \tabsolute or relative paths are both ok."
    exit 1 # Exit script after printing help
}

findAllFolder(){
    # echo "new findAllFolder in $1"
    cd $1
    for sub in $(ls $1); do
        if (test -d ${sub}) ; then
            SUCCESSOR_DIR=$( cd $1/${sub} && pwd)
            if (isGitRepo ${SUCCESSOR_DIR}); then
                echo "${SUCCESSOR_DIR} is a git repository."
                GIT_REPO_DIR[ITER]=${SUCCESSOR_DIR}
                ITER=$[ ${ITER} + 1 ] # ITER=${ITER}+1 is also Okay.
            else
                # echo "${SUCCESSOR_DIR} is a normal folder."
                findAllFolder ${SUCCESSOR_DIR}
            fi
        fi
    done
    cd ..
    # pwd
}

isGitRepo(){
    # 0 - true; 1 - false
    CANDIDATE_DIR=$1
    if [ $(ls -al ${CANDIDATE_DIR} | grep "^d" | grep -w ".git" | wc -l) -eq 1 ]; then
        return 0
    else
        return 1
    fi
}

main(){
    if [ $# -eq 0 ] || [ $# -gt 1 ] || [ $1 = "-h" ] || [ $1 = "--help" ] ; then
        helpFunction
    fi
    BASE_DIR=$(cd $1 && pwd)
    echo -e "\033[36m current dir is: ${BASE_DIR} \033[0m"
    cd ${BASE_DIR}
    findAllFolder ${BASE_DIR}
    export GIT_REPO_DIR # use source ./*.sh to export variable
    echo "Found Git repositories: ${#GIT_REPO_DIR[*]}"
}

main $@



